### PR TITLE
Fix read frame for thread decoding

### PR DESCRIPTION
**Pull request by xiaotianshi2**
update h264dec.cpp's readPicture to make it to read a complete frame at a time for thread-decoding of multi-slice frame.

### CODE REVIEW

**Comment by huili2** [comment]
it is rather weird to implement entropy decoding in console code....

**Comment by xiaotianshi2** [comment]
@huili2 Right, it is.  However, this is just for h264dec test purpose. In real-world (for example ffmpeg AVCodec), the input buffer is always  a frame and it does not need to call this function.

**Comment by huili2** [comment]
thanks. could you please make a clean commit, to remove "merge" one? Thanks.

**Comment by xiaotianshi2** [comment]
Sure and will do so (I was wondering how that "merge" one got in).

**Comment by xiaotianshi2** [comment]
not a clean PR and so close it.

**Pull request closed without merging**
