### PR TITLE
[Processing/x86] GeneralBilinearDownsample optimizations

### PR DESCRIPTION
**Pull request by saamas**
https://rbcommons.com/s/OpenH264/r/1608/
https://rbcommons.com/s/OpenH264/r/1609/
https://rbcommons.com/s/OpenH264/r/1610/
https://rbcommons.com/s/OpenH264/r/1611/
https://rbcommons.com/s/OpenH264/r/1612/
https://rbcommons.com/s/OpenH264/r/1613/

### CODE REVIEW

**Comment by mstorsjo** [comment]
I think this merge (or some of the related ones) may be responsible for the issues I'm seeing with valgrind now (discussed in #2476), reproducible (for me) on linux with the following commands:

    make BUILDTYPE=Debug USE_ASM=Yes -j4
    valgrind ./codec_unittest --seed=3 --gtest_filter=EncoderInterfaceTest.MemoryCheckTest

(If no errors are shown, try with a few different seeds - I was able to find it by going from 0 to 3.)

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1608/

----
**testing_done**:  
**description**:  [Processing] Reduce duplication in downsampling wrappers

----
 reviewer Karina Li (ruil2) 
 time 2016-05-26T04:15:33+00:00 
2016-05-26T04:15:33+00:00 Karina Li (ruil2):
>Ship It!
Ship It!
Ship it!


----

----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1608/

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1609/

----
**testing_done**:  
**description**:  <p>Keep track of relative pixel offsets and utilize pshufb to efficiently<br />extract relevant pixels for horizontal scaling ratios &lt;= 4.</p><p>Fall back to a generic approach for ratios &gt; 4. Note that the generic<br />approach can be backported to SSE2.</p><p>The implementation assumes that data beyond the end of each line,<br />before the next line begins, can be dirtied; which AFAICT is safe with<br />the current usage of these routines.</p><p>Speedup is ~6.67x/~3.26x (32-bit/64-bit) for horizontal ratios &lt;= 2,<br />~6.24x/~3.00x for ratios within (2, 4], and ~4.89x/~2.17x for ratios<br />> 4 when not memory-bound on Haswell as compared with the current SSE2<br />implementation.</p>

----
 reviewer Karina Li (ruil2) 
 time 2016-05-26T04:15:22+00:00 
2016-05-26T04:15:22+00:00 Karina Li (ruil2):
>Ship It!
Ship It!
Ship it!


----

----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1609/

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1610/

----
**testing_done**:  
**description**:  <p>Keep track of relative pixel offsets and utilize pshufb to efficiently<br />extract relevant pixels for horizontal scaling ratios &lt;= 4.</p><p>Fall back to a generic approach for ratios &gt; 4.</p><p>The use of blendps makes this require SSE4.1. The pshufb path can be<br />backported to SSSE3 and the generic path to SSE2 for a minor reduction<br />in performance by replacing blendps and preceding instructions with an<br />equivalent sequence.</p><p>The implementation assumes that data beyond the end of each line,<br />before the next line begins, can be dirtied; which AFAICT is safe with<br />the current usage of these routines.</p><p>Speedup is ~5.32x/~4.25x (32-bit/64-bit) for horizontal ratios &lt;= 2,<br />~5.06x/~3.97x for ratios within (2, 4], and ~3.93x/~3.13x for ratios<br />> 4 when not memory-bound on Haswell as compared with the current SSE2<br />implementation.</p>

----
 reviewer Karina Li (ruil2) 
 time 2016-05-26T04:15:11+00:00 
2016-05-26T04:15:11+00:00 Karina Li (ruil2):
>Ship It!
Ship It!
Ship it!


----

----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1610/

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1611/

----
**testing_done**:  
**description**:  <p>Keep track of relative pixel offsets and utilize pshufb to efficiently<br />extract relevant pixels for horizontal scaling ratios &lt;= 8. Because<br />pshufb does not cross 128-bit lanes, the overhead of address<br />calculations and loads is relatively greater as compared with an<br />SSSE3 implementation.</p><p>Fall back to a generic approach for ratios &gt; 8.</p><p>The implementation assumes that data beyond the end of each line,<br />before the next line begins, can be dirtied; which AFAICT is safe with<br />the current usage of these routines.</p><p>Speedup is ~10.42x/~5.23x (32-bit/64-bit) for horizontal ratios &lt;= 2,<br />~9.49x/~4.64x for ratios within (2, 4], ~6.43x/~3.18x for ratios<br />within (4, 8], and ~5.42x/~2.50x for ratios &gt; 8 when not memory-bound<br />on Haswell as compared with the current SSE2 implementation.</p>

----
 reviewer Karina Li (ruil2) 
 time 2016-05-26T04:15:02+00:00 
2016-05-26T04:15:02+00:00 Karina Li (ruil2):
>Ship It!
Ship It!
Ship it!


----

----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1611/

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1612/

----
**testing_done**:  
**description**:  <p>Keep track of relative pixel offsets and utilize pshufb to efficiently<br />extract relevant pixels for horizontal scaling ratios &lt;= 8. Because<br />pshufb does not cross 128-bit lanes, the overhead of address<br />calculations and loads is relatively greater as compared with an<br />SSSE3/SSE4.1 implementation.</p><p>Fall back to a generic approach for ratios &gt; 8.</p><p>The implementation assumes that data beyond the end of each line,<br />before the next line begins, can be dirtied; which AFAICT is safe with<br />the current usage of these routines.</p><p>Speedup is ~8.52x/~6.89x (32-bit/64-bit) for horizontal ratios &lt;= 2,<br />~7.81x/~6.13x for ratios within (2, 4], ~5.81x/~4.52x for ratios<br />within (4, 8], and ~5.06x/~4.09x for ratios &gt; 8 when not memory-bound<br />on Haswell as compared with the current SSE2 implementation.</p>

----
 reviewer Karina Li (ruil2) 
 time 2016-05-24T06:25:47+00:00 
2016-05-24T06:25:47+00:00 Karina Li (ruil2):
><p>Can travis CI run on AVX2 case?</p>
Can travis CI run on AVX2 case?

2016-05-24T07:15:02+00:00 Karina Li (ruil2):
><p>Yes, travis does appear to run the AVX2 tests:<br />https://travis-ci.org/saamas/openh264/builds/132473843</p>
very appreciate your working on the performance improvment continuously.
Yes, travis does appear to run the AVX2 tests:<br />https://travis-ci.org/saamas/openh264/builds/132473843


----
 reviewer Karina Li (ruil2) 
 time 2016-05-26T04:14:46+00:00 
2016-05-26T04:14:46+00:00 Karina Li (ruil2):
>Ship It!
Ship It!
Ship it!


----

----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1612/

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1613/

----
**testing_done**:  
**description**:  Get coverage of all code paths for routines that branch to differentpaths for different scaling ratios.

----
 reviewer Karina Li (ruil2) 
 time 2016-05-24T08:06:59+00:00 
2016-05-24T08:06:59+00:00 Karina Li (ruil2):
 on **test/processing/ProcessUT_DownSample.cpp line305**: 
 id="comment397671"><p>should destination height change to cover different ratio?</p>
should destination height change to cover different ratio?


----
2016-05-25T12:49:42+00:00 status-change:
Also test a wider variety of height ratios.


----
 reviewer Karina Li (ruil2) 
 time 2016-05-26T04:14:37+00:00 
2016-05-26T04:14:37+00:00 Karina Li (ruil2):
>Ship It!
Ship It!
Ship it!


----

----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1613/

**Pull request merged**
