### PR TITLE
easy build with Android SDK circa 2020 and NDK r20 (also r21)

### PR DESCRIPTION
**Pull request by alexcohn**
switch from ant to gradle
look at the commonly defined ANDROID_HOME and ANDROID_NDK_ROOT env variables
don't need $(ANDORID_HOME)/tools to be on PATH

This should answer https://github.com/cisco/openh264/issues/3051 https://github.com/cisco/openh264/issues/3069 https://github.com/cisco/openh264/issues/3107 https://github.com/cisco/openh264/issues/3234 https://github.com/cisco/openh264/issues/3250 https://github.com/cisco/openh264/issues/3251

### CODE REVIEW

**Comment by alexcohn** [comment]
I notice that the Android SDK dependency is only to build the 'test' apks and run them. With the new SDK, we don't have `android project` anymore. I overcame this here by switching to gradle build, but this is kind of abusing the system. There are two alternatives, IMO. One is to create better integration with Android Studio and Android Gradle plugin, and convert the tests into [Android Instrumented Tests](https://developer.android.com/studio/test#create_instrumented_test_for_a_build_variant). The other, tune the `runTest.sh` script to run (optionally) the command-line gtest on Android device (or emulator).

**Comment by GuangweiWang** [comment]
thanks!

**Comment by martsa** [comment]
guys i am not able to build openH264 library .. please help me at my issue https://github.com/cisco/openh264/issues/3318

**Comment by ade** [comment]
I was struggling for a while to get this to work when building with OpenH264 2.1.1 and NDK r21e. Well, turns out that wasn't very strange, as this commit hasn't actully been merged to any release, it's just on a branch named openh264v2.1.0. Any chance of getting this merged to a release?

**Comment by zhutq** [comment]
@GuangweiWang could help with this? ^^ Thank you!

**Comment by emretufekci** [comment]
with this branch which is https://github.com/cisco/openh264/tree/openh264v2.1.0
Gradle version: 6.1.1

By running this:
`make OS=android NDKROOT=/home/emre/Desktop/TEST/pj-original/android-ndk-r21e TARGET=android-29 ARCH=arm64`

I'm getting this error:
```
make[1]: Leaving directory '/home/emre/Desktop/TEST/pj-original/openh264/codec/build/android/dec'
./gradlew test-dec:assembleDebug
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
make: *** [build/platform-android.mk:101: decdemo] Error 1
```
It's confusing, seems i built .so files successfully but gradle tests not okay i guess.

**Comment by aenonGit** [comment]
> with this branch which is https://github.com/cisco/openh264/tree/openh264v2.1.0
> Gradle version: 6.1.1
> 
> By running this:
> `make OS=android NDKROOT=/home/emre/Desktop/TEST/pj-original/android-ndk-r21e TARGET=android-29 ARCH=arm64`
> 
> I'm getting this error:
> 
> ```
> make[1]: Leaving directory '/home/emre/Desktop/TEST/pj-original/openh264/codec/build/android/dec'
> ./gradlew test-dec:assembleDebug
> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
> make: *** [build/platform-android.mk:101: decdemo] Error 1
> ```
> 
> It's confusing, seems i built .so files successfully but gradle tests not okay i guess.

that's because it can't build encoder and decoder demo, you should skip them in makefile

**Pull request merged**
