### PR TITLE
B-frame decoding support for Main and High Profile with two test cases.

### PR DESCRIPTION
**Pull request by xiaotianshi2**
This new fork has exact source code changes as my previous fork https://github.com/xiaotianshicomcast/openh264. The reason is doing this that it is not easy to clean the failed history even by squashing commits.

### CODE REVIEW

**Comment by huili2** [comment]
for function ReorderRefList2(), I find there is no error protect like in ReorderRefList(). Would you add in the future?

**Comment by xiaotiansf** [comment]
@huili2 
Certainly I'll. I will need more testing before activating it although ReorderRefList2() does work with my a few test cases with multi-reference with B-frame.

**Comment by fiona22** [comment]
Hi, xiaotianshi, I used JM to generate B frames bitstreams, and used your pr2991 to decode these bitstreams, it could only decode 2 frames(setting to 9 frames), but JSVM and JM itself decoded them correctly.

The test bitstreams are BasketballDrill_832x480_50.264 and Cactus_1920x1080_50.264.

[Bframes bitstreams.zip](https://github.com/cisco/openh264/files/2226990/Bframes.bitstreams.zip)

The ouput of decode using pr2991:
https://engci-private-sjc.cisco.com/jenkins/wme/view/openh264/job/video-codec/job/openh264/view/3-Conformance-Test/job/openh264-conformance-test-decoder/97/console

**Comment by xiaotianshi2** [comment]
@fiona22
Could you try again to verify my fix?
Thanks.

**Comment by fiona22** [comment]
sure, i'll.

**Comment by chezhan3** [comment]
@xiaotianshi2 Thanks for your effort, I have tested again, this bug was fixed.

**Comment by sijchen** [comment]
@xiaotianshi2  thank you for all the fixes!

**Pull request merged**
