### PR TITLE
fix source picture error mapping issue

### PR DESCRIPTION
**Pull request by ruil2**
reviewed at:https://rbcommons.com/s/OpenH264/r/1734/

### CODE REVIEW

**Comment by PeterXu** [comment]
draw bach this pull request, I will create a new.

**Comment by PeterXu** [comment]
It is ok now, but there exist another issue in testing 90p:
   When the image of camera is still for some time, and then some objects begin moving.
   The encoded output have a obvious sluggish trailing.
   What is the reason?  the chosen ref-pic is not suitable?

**Comment by huili2** [comment]
@PeterXu This PR fixes the issue you raised. For other new bugs, you may open new issues tracing  them :). Close this one.

**Comment by ruil2** [comment]
@PeterXu  you can submit an issue to give more details about "sluggish trailing"? thanks!

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1734/

----
**testing_done**:  
**description**:  fix source picture error mapping issue

----
 reviewer wayne liu (huili2) 
 time 2016-11-27T22:37:39-08:00 
2016-11-27T22:37:39-08:00 wayne liu (huili2):
><p>seems OK to me.</p>
seems OK to me.
Ship it!


----

----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1734/

**Pull request merged**
