### PR TITLE
Add fuzzing to CI

### PR DESCRIPTION
**Pull request by jrmuizel**
This is currently broken because of #3536

### CODE REVIEW

**Comment by jrmuizel** [comment]
It looks like https://github.com/mozillasecurity/fuzzdata.git/trunk/samples/h264 can't be accessed. @tysmith do you know what might be going on here?

**Comment by jrmuizel** [comment]
@jschwartzentruber is taking a look

**Comment by tysmith** [comment]
This should be fixed by https://github.com/google/oss-fuzz/pull/11207

**Comment by mstorsjo** [comment]
> This should be fixed by [google/oss-fuzz#11207](https://github.com/google/oss-fuzz/pull/11207)

Right, so someone should update the fuzz job here in this repo as well, to do something similar?

**Comment by jrmuizel** [comment]
Nope, things should just work now.

**Comment by mstorsjo** [comment]
> Nope, things should just work now.

Hmm, I just retried a job, and it failed again: https://github.com/mstorsjo/openh264/actions/runs/6796632625/job/18542284463

```
+ svn export https://github.com/mozillasecurity/fuzzdata.git/trunk/samples/h264 corpus/
svn: E170013: Unable to connect to a repository at URL 'https://github.com/mozillasecurity/fuzzdata.git/trunk/samples/h264'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
```

**Comment by tysmith** [comment]
The above PR has not been merged yet.

**Comment by mstorsjo** [comment]
> The above PR has not been merged yet.

Ah, I see - sorry for the too hasty conclusion.

**Comment by mstorsjo** [comment]
Ok, now this seems to work again. Thanks!

**Pull request merged**
