### PR TITLE
fix unsigned integer(uint32_t) overflow

### PR DESCRIPTION
**Pull request by skzxcc**

### CODE REVIEW

**Comment by jrmuizel** [comment]
Do you have a test case that triggers this?

**Comment by skzxcc** [comment]
It's easily triggered when working with HD video sources with complex textures on BitrateMode ratecontrol
you can trigger it,  run ".\encConsole.exe test-welsenc.cfg"















At 2022-10-08 22:19:10, "Jeff Muizelaar" ***@***.***> wrote:

Do you have a test case that triggers this?

**Comment by huili2** [comment]
still suggest have a detailed case for debugging, as this will be assigned to other variables.

**Comment by skzxcc** [comment]
> 仍然建议有一个详细的案例进行调试，因为这将被分配给其他变量。

Can you provide an email address? I will send you the video source file and configuration file,  you can easily trigger it.

**Pull request closed without merging**
