### PR TITLE
slice buffer reallocate enable for size_limit slice mode under multi thread

### PR DESCRIPTION
**Pull request by shihuade**
Test:
1. Travis:
  [UT for new reallocate design ](https://travis-ci.org/shihuade/openh264/builds/199528257)  
2. Conformance Test: 
    [openh264 conformance test ](http://10.140.198.27:8080/view/SGE-Test/job/Openh264-SGE-Job-status-And-TestResult/962/artifact/Openh264-SGETest/Jenkins-Job-Submit-Log/)
   [latest test](http://10.140.198.27:8080/view/SGE-Test/job/Openh264-SGE-Job-Submit/)

3.  Release test:
   [Jenkins release test](http://10.140.198.27:8080/view/Pipeline/job/Pipeline-Test/)

Review history:
      [latest code review for design series](https://rbcommons.com/s/OpenH264/r/1766/)

Doc for new design:
      [NewSliceBufferDesign.pdf](https://github.com/shihuade/openh264/blob/MultiThread_V9.1_withDoc/docs/NewSliceBufferDesign.pdf)

### CODE REVIEW

**Comment by huili2** [comment]
is it necessary to have so many commits?

**Comment by shihuade** [comment]
@huili2  code change in this PR is huge, so if using one commit, it is difficult to do code review.
and for later trouble shooting, small commit is prefer

**Comment by sijchen** [comment]
@shihuade , you can always do cherry-picking to make PR smaller.
this PR is too huge and mixing things up.
(1) some of the code changes are not accepted by code review
(2) some the change changes doesn't look like correct. for example, in commit 03972ae , which do the changes mean with the file test/build/win32/codec_ut/Codec_UT.sln?
(3) we've mentioned that we will try best to avoid changing so many codes along with the binary results in one PR.
Conclusively, I would rather close this PR. Please submit the changes in smaller PRs.

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1766/

----
**testing_done**:  
**description**:  <ol><li><p>GetInitialSliceNum()<br />   ----remove input parameters kiMbWidth/kiMbHeight<br />   ----update call module which call ()<br />       like: InitSliceList() etc.</p></li><li><p>Change AcquireLayersNals() frome static function to normal function as call by ut module;</p></li><li><p>Add ut case for slice buffer reallocate feature<br />   6 UT cases for:<br />      ----InitAllSlicesInThread()<br />      ----ReallocateSliceInThread()<br />      ----ReallocateSliceList()<br />      ----FrameBsRealloc()<br />      ----ReOrderSliceInLayer()<br />      ----SliceLayerInfoUpdate()</p></li><li><p>Update windows ut project</p></li><li><p>Update Mac/linux ut make file</p></li></ol>

----
2017-02-08T08:00:19+00:00 status-change:
fixed travis error


----
 reviewer Forrest Shi (huade) 
 time 2017-02-08T08:41:53+00:00 
2017-02-08T08:41:53+00:00 Forrest Shi (huade):
><p>help to review previous series,<br />review num is :(15 review request)<br />    #1710 #1711 #1712 #1713 #1715 #1716 #1719<br />    #1720 #1721 #1723 #1725 #1726 <br />    #1751 #1752 #1753 <br />Thanks</p>
help to review previous series,<br />review num is :(15 review request)<br />    #1710 #1711 #1712 #1713 #1715 #1716 #1719<br />    #1720 #1721 #1723 #1725 #1726 <br />    #1751 #1752 #1753 <br />Thanks


----
 reviewer Sijia Chen (sijchen) 
 time 2017-03-29T17:38:54+00:00 
2017-03-29T17:38:54+00:00 Sijia Chen (sijchen):
 on **test/build/win32/codec_ut/Codec_UT.sln line2**: 
 id="comment524402"><p>are these changes of sln needed? do we plan to release vs2013 sln now?</p>
are these changes of sln needed? do we plan to release vs2013 sln now?

2017-04-07T03:04:53+00:00 Forrest Shi (huade):
><p>has been removed and keep origin VS2008 project</p>
has been removed and keep origin VS2008 project

2017-04-07T03:04:53+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.h line5**: 
 id="comment524404"><p>pls use MAX_FS as in level5.1/5.2 to set the max size</p>
pls use MAX_FS as in level5.1/5.2 to set the max size

2017-04-19T15:29:16+00:00 Forrest Shi (huade):
><p>so what you mean:<br />1. using MaxFS = 36864 (which 36864 = (4096 x 2304) / (16 * 16))<br />2. and come case may&gt; PicW &gt;4096, than limit the PicH and let it be PicH &lt; MaxFS/PicW ?</p><p>if so, I don't think it is good test case for common use.</p>
will add it in next diff version
by MAX_FS i mean max-frame-size. so the MAX_WIDTH and MAX_HEIGHT shouldn't be limited to 4k in test cases.
https://rbcommons.com/s/OpenH264/r/1766/diff/3-5/
no, I mean that, with a MAX-FRAMESIZE limit, the height can be 4096 and the width can be 2304. restricting the ratio does not seem to be a good test case codes.
so what you mean:<br />1. using MaxFS = 36864 (which 36864 = (4096 x 2304) / (16 * 16))<br />2. and come case may&gt; PicW &gt;4096, than limit the PicH and let it be PicH &lt; MaxFS/PicW ?
if so, I don't think it is good test case for common use.

2017-04-19T15:29:16+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line145**: 
 id="comment524420"><p>where in this function has codes related to "paramset"?</p>
where in this function has codes related to "paramset"?

2017-04-07T18:06:05+00:00 Forrest Shi (huade):
><p>I see this function called.</p><p>I mean the name is a bit misleading, you actually mean "SettingParametersForReallocationTest"<br />But the term "ParamSet" tends to confuse with "parameter set"(SPS/PPS).</p>
TEST_F(CSliceBufferReallocatTest, Reallocate_in_one_partition)<br />and<br />TEST_F(CSliceBufferReallocatTest, Reallocate_in_one_thread)
I see this function called.
I mean the name is a bit misleading, you actually mean "SettingParametersForReallocationTest"<br />But the term "ParamSet" tends to confuse with "parameter set"(SPS/PPS).

2017-04-07T18:06:05+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line216**: 
 id="comment524408"><p>when you want to test buffer re-allocation, clipping qp to 26 is not a good idea, should allow very low qp</p>
when you want to test buffer re-allocation, clipping qp to 26 is not a good idea, should allow very low qp

2017-04-18T01:23:28+00:00 Forrest Shi (huade):
><p>https://rbcommons.com/s/OpenH264/r/1766/diff/5-6/</p>
so what's your suggestion for low qp, I set it to 12, is it low enough?
will setting to 0 make the test work?
https://rbcommons.com/s/OpenH264/r/1766/diff/5-6/

2017-04-18T01:23:28+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line323**: 
 id="comment524410"><p>it doesn't look like that this file is well formatted as suggested</p>
it doesn't look like that this file is well formatted as suggested

2017-04-28T02:53:31+00:00 Forrest Shi (huade):
><p>https://rbcommons.com/s/OpenH264/r/1821/</p>
will astyle later
https://rbcommons.com/s/OpenH264/r/1821/

2017-04-28T02:53:31+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line422**: 
 id="comment524415"><p>ReallocateTest_01 is not a good naming, I'd rather see it changed into something like "reallocate_in_one_partition"</p>
ReallocateTest_01 is not a good naming, I'd rather see it changed into something like "reallocate_in_one_partition"

2017-04-07T03:04:53+00:00 Forrest Shi (huade):
><p>good suggestion</p>
good suggestion

2017-04-07T03:04:53+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line433**: 
 id="comment524416"><p>do you mean "//case: reallocate during encoding one partition"</p>
do you mean "//case: reallocate during encoding one partition"

2017-04-07T18:13:31+00:00 Forrest Shi (huade):
><p>pls fix the grammar then</p>
yes
pls fix the grammar then

2017-04-07T18:13:31+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line435**: 
 id="comment524418"><p>"less than" or "more than"?</p>
"less than" or "more than"?

2017-04-07T03:04:53+00:00 Forrest Shi (huade):
><p>lest than.<br />example,  pCtx-&gt;iActiveThreadsNum = 3, <br />          iPartitionNum  may equal to 1 or 2 or 3.<br />          1 or 2 is lesst than iActiveThreadsNum</p>
lest than.<br />example,  pCtx-&gt;iActiveThreadsNum = 3, <br />          iPartitionNum  may equal to 1 or 2 or 3.<br />          1 or 2 is lesst than iActiveThreadsNum

2017-04-07T03:04:53+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line440**: 
 id="comment524431"><p>if you need to release memory later pls use EXPECT_TRUE rather than ASSERT_TRUE</p>
if you need to release memory later pls use EXPECT_TRUE rather than ASSERT_TRUE

2017-04-18T01:23:28+00:00 Forrest Shi (huade):
><p>https://rbcommons.com/s/OpenH264/r/1766/diff/5-6/</p>
replace all ASSERT_TRUE to EXPECT_TRUE
https://rbcommons.com/s/OpenH264/r/1766/diff/5-6/

2017-04-18T01:23:28+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line443**: 
 id="comment524433"><p>suggest to add a check for the slice content. for example, manually set some value in the slice content before re-allocate and check if the value is correct after re-allocate.</p>
suggest to add a check for the slice content. for example, manually set some value in the slice content before re-allocate and check if the value is correct after re-allocate.

2017-04-07T18:13:31+00:00 Forrest Shi (huade):
><p>try directly writing a value to a variable in the slice context before reallocation.</p>
good suggestion, but seems it is too difficult to check it, need more detail for the impletment
try directly writing a value to a variable in the slice context before reallocation.

2017-04-07T18:13:31+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line458**: 
 id="comment524412"><p>do you mean "all partitions encoded by one thread"</p>
do you mean "all partitions encoded by one thread"

2017-04-07T18:13:31+00:00 Forrest Shi (huade):
><p>pls fix the grammar then</p>
yes! it is corner case but still need to check<br />example: 3 threads 3 partions<br />         thrd_0:  partion_0 --&gt;partition_1 --&gt;partition_2<br />         thrd_1:  idle<br />         thrd_2:  idle
pls fix the grammar then

2017-04-07T18:13:31+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line466**: 
 id="comment524430"><p>are ln439-442 the same to here ln466-471?</p>
are ln439-442 the same to here ln466-471?

2017-04-28T03:21:18+00:00 Forrest Shi (huade):
><p>only used in two location, no need here</p>
yes, the initial value before reallocate
can you wrap duplicated codes then
only used in two location, no need here

2017-04-28T03:21:18+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line509**: 
 id="comment524435"><p>suggest to add a check for the content. for example, manually set some value in first mb list before re-allocate and check if the value is correct after re-allocate.</p>
suggest to add a check for the content. for example, manually set some value in first mb list before re-allocate and check if the value is correct after re-allocate.

2017-04-07T03:04:53+00:00 Forrest Shi (huade):
><p>good suggestion, but seems it is too difficult to check it, need more detail for the impletment</p>
good suggestion, but seems it is too difficult to check it, need more detail for the impletment

2017-04-07T03:04:53+00:00 Forrest Shi (huade):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line539**: 
 id="comment524436"><p>repeated?</p>
repeated?

2017-04-07T03:04:53+00:00 Forrest Shi (huade):
><p>done, has been removed</p>
done, has been removed


----
2017-04-07T03:09:43+00:00 status-change:
update review based on sijia's suggestion


----
2017-04-07T06:16:54+00:00 status-change:
add max sample size per second limitation based on level 5.2


----
2017-04-07T06:28:13+00:00 status-change:
update branch name


----
2017-04-07T07:41:58+00:00 status-change:
fixed bug for max frame rate setting


----
 reviewer Sijia Chen (sijchen) 
 time 2017-04-07T18:16:26+00:00 
2017-04-07T18:16:26+00:00 Sijia Chen (sijchen):
 on **test/encoder/EncUT_SliceBufferReallocate.h line20**: 
 id="comment528959"><p>still should use EXPECT not ASSERT when there is some memory allocated before</p>
still should use EXPECT not ASSERT when there is some memory allocated before

2017-04-10T10:13:15+00:00 wayne liu (huili2):
><p>Actually it is not good to do big memory allocation in SetUp(), as ASSERT_XXX () just return, but not exit current test, if it it false.</p>
Actually it is not good to do big memory allocation in SetUp(), as ASSERT_XXX () just return, but not exit current test, if it it false.


----
2017-04-11T02:32:19+00:00 status-change:
change test QP range


----
 reviewer Sijia Chen (sijchen) 
 time 2017-04-14T21:23:04+00:00 
2017-04-14T21:23:04+00:00 Sijia Chen (sijchen):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line324**: 
 id="comment531357"><p>still have format prob</p>
still have format prob

2017-04-28T02:52:47+00:00 Forrest Shi (huade):
><p>astyled, you can refer to https://rbcommons.com/s/OpenH264/r/1821/</p>
astyled, you can refer to https://rbcommons.com/s/OpenH264/r/1821/


----
 reviewer Sijia Chen (sijchen) 
 time 2017-04-18T22:41:34+00:00 
2017-04-18T22:41:34+00:00 Sijia Chen (sijchen):
Ship it!

2017-04-18T22:41:34+00:00 Sijia Chen (sijchen):
 on **test/encoder/EncUT_SliceBufferReallocate.cpp line449**: 
 id="comment532559"><p>I am not seeing this name changed. why we set the issue to be fixed?</p>
I am not seeing this name changed. why we set the issue to be fixed?

2017-04-28T03:20:21+00:00 Forrest Shi (huade):
><p>https://rbcommons.com/s/OpenH264/r/1823/</p>
https://rbcommons.com/s/OpenH264/r/1823/


----

----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1766/

**Pull request closed without merging**
