### PR TITLE
Add AArch64 to CI

### PR DESCRIPTION
**Pull request by jrmuizel**
This cross compiles for AArch64 and runs the unit tests using qemu-user

### CODE REVIEW

**Comment by GuangweiWang** [comment]
looks good to me

**Comment by GuangweiWang** [comment]
what the difference between these two method:

 aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  |
         sudo dpkg --add-architecture aarch64
         run: sudo apt-get update -qq
         run: sudo apt-get install -qq gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user
         run: c++ --version
         run: make gmp-bootstrap
         run: make gtest-bootstrap
         run: make OS=linux CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ ARCH=arm64
         run: qemu-aarch64 -L /usr/aarch64-linux-gnu/ ./codec_unittest

**Comment by jrmuizel** [comment]
The yaml syntax? I was aiming for consistency with the other targets.

**Comment by jrmuizel** [comment]
Closing in favor of #3531 now that #3528 has been merged.

**Pull request closed without merging**
