### PR TITLE
Add cabac_bframe bitstreams to openh264/res

### PR DESCRIPTION
**Pull request by chezhan3**

### CODE REVIEW

**Comment by mstorsjo** [comment]
Does this commit change 2 of the existing cavlc+bframes sample files?

**Comment by chezhan3** [comment]
@mstorsjo No, these 2 b-frame bitstreams are generated by JM, and they are new.

**Comment by mstorsjo** [comment]
Oh, I misread the commit - this removes two of the existing ones, renames one of the existing ones and adds one new.

I'm not sure how good test sample this is though; there's almost literally no motion at all in these test clips, only the blinking cursor changing from each frame to the next?

**Comment by chezhan3** [comment]
Hi,
   Yes, it is a still photo with 9 frames. With cabac+b frame to decode, it could decode, but with cavlc+b frame to decode, it failed. Probably, it's the problem of not supporting cavlc+b frame, and there is no problem with test cases.
Br,
Chen Zhang -X (chezhan3 - CIIC at Cisco)
[https://www.cisco.com/c/dam/m/en_us/signaturetool/images/logo/Cisco_Logo_no_TM_Medium_Gray-RGB_43px.png]




Chen Zhang
Intern
chezhan3@cisco.com<mailto:chezhan3@cisco.com>
Tel:










Cisco Systems, Inc.



China
cisco.com



[http://www.cisco.com/assets/swa/img/thinkbeforeyouprint.gif]

Think before you print.

This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
Please click here<http://www.cisco.com/c/en/us/about/legal/terms-sale-software-license-agreement/company-registration-information.html> for Company Registration Information.

**Pull request merged**
