### PR TITLE
More fixes for out-of-tree build:

### PR DESCRIPTION
**Pull request by ghismary**
- Generate version header in the build tree
 - Generate .res file in the build tree on Windows
 - Add the $(SRC_PATH) prefix to the .def files on Windows

### CODE REVIEW

**Comment by mstorsjo** [comment]
Except for the detail about `//fo` vs `-fo`, these changes look good to me.

**Comment by sijchen** [comment]
@ghismary could you kindly add a commit to fix the detail as mentioned above in comments? Thanks a lot.

**Comment by ghismary** [comment]
I have added the commit to replace the /fo option by -fo.

**Comment by sijchen** [comment]
@ghismary thanks a lot.

**Pull request merged**
