### PR TITLE
Pr multi refs encode

### PR DESCRIPTION
**Pull request by fulinjie**
Found some potential issues while enabling multi refs encoding in FFmpeg.
Please help to comment.

### CODE REVIEW

**Comment by fulinjie** [comment]
Hi @ruil2 , would you please help to review and offer some comments?

**Comment by huili2** [comment]
the first commit is OK from my side. I'm wondering the "loosing" reason? May it affect the original reference picture settings in hierarchical structures?

**Comment by fulinjie** [comment]
The main reason for loosing this check is to allow automatically adjusting the settings of reference number inside libopenh264 with a warning prompted for user, instead of failing directly.

IMHO this would be more robust/compatible for users if they didn't know the constraints of reference number and keep the encoder working.

For example, if setting -refs 3 in FFmpeg (require reference to 3),
libopenh264 would report warnings like:
iNumRefFrame(3) setting does not support the temporal and LTR setting, will be reset to 4.

After reset the reference, encoder could work well.

Ps, I'm not strongly insisting on this, if it breaks something I didn't noticed.
Feel free to only apply the first commit which is functional, thx.

**Comment by fulinjie** [comment]
ping.

**Comment by fulinjie** [comment]
Hi @huili2, any updates?

**Comment by huili2** [comment]
sorry late for this. I'm OK for this PR.

**Comment by fulinjie** [comment]
Thanks for the review.

**Comment by mstorsjo** [comment]
This change broke 18 tests in EncodeFile/EncoderOutputTest - please update the test references accordingly.

**Comment by mstorsjo** [comment]
Just FWIW, I sent a fix for the test references in #3272.

**Pull request merged**
