### PR TITLE
Revert "[Encoder] fix for in-middle changing simulcast avc setting"

### PR DESCRIPTION
**Pull request by lililya**

### CODE REVIEW

**Comment by ethanhugg** [comment]
There is no comment here saying why you think it's a good idea to revert this.

**Comment by sijchen** [comment]
@lililya, hi please give you reasons if you want to revert other's commit, and please close this pull request if this is not what you want. 
@lililya, 您好, 在这里您提出了一个取消(revert)某个commit的pull request, 换句话说, 您在要求把一个已经放到代码里面的更改回滚. 如果您认为之前的这个更改不适当, 您需要在这里给出原因, 如果这是您的误操作, 希望您取消这个pull request. 请尊重他人在这个公开代码库中的劳动, 谢谢.

**Comment by lililya** [comment]
如果哪里冒犯了对不起，只是语言不通，翻译的完全不是那个意思，我都吧明白，代码回滚，是什么意思啊



lililya521@outlook.com
 
From: sijchen
Date: 2015-02-09 10:49
To: cisco/openh264
CC: lililya
Subject: Re: [openh264] Revert "[Encoder] fix for in-middle changing simulcast avc setting" (#1806)
@lililya, hi please give you reasons if you want to revert other's commit, and please close this pull request if this is not what you want. 
@lililya, 您好, 在这里您提出了一个取消(revert)某个commit的pull request, 换句话说, 您在要求把一个已经放到代码里面的更改回滚. 如果您认为之前的这个更改不适当, 您需要在这里给出原因, 如果这是您的误操作, 希望您取消这个pull request. 请尊重他人在这个公开代码库中的劳动, 谢谢.

**Comment by ottersxx** [comment]
revert 就是回滚吧， rollback？

**Comment by sijchen** [comment]
when you want to revert a commit you mean to rollback the code changes, meaning that you want to take those changes out of the current codes.
revert某个更改相当于回滚(rollback)这个更改, 也就是把这部分更改从现有的代码里面取出来(删除).

**Pull request closed without merging**
