### PR TITLE
update enc metrics QP

### PR DESCRIPTION
**Pull request by huili2**
to fix https://github.com/cisco/openh264/issues/3317

### CODE REVIEW

**Comment by jrmuizel** [comment]
Can this have a test?

**Comment by huili2** [comment]
@jrmuizel do you find any wrong info about this PR?

**Comment by jrmuizel** [comment]
Nope, just wondering if it makes sense for there to be a test that checks if the metrics are properly filled out.

**Comment by huili2** [comment]
I thought it would be correct, but not sure. Let me double check.

**Comment by huili2** [comment]
Checked the code, it should be OK (stands for the last frame's average qp).

**Pull request merged**
