### PR TITLE
Openh264v1.0

### PR DESCRIPTION
**Pull request by hobochen163**

### CODE REVIEW

**Comment by radhikasim** [comment]
[830E9C5A45A805B87FDDF591DABD883705EE.pdf](https://github.com/cisco/openh264/files/1151266/830E9C5A45A805B87FDDF591DABD883705EE.pdf)

**Comment by Jay-Tarzan** [comment]
closed (?) red

**Comment by Jay-Tarzan** [comment]
download pdf

**Comment by GuangweiWang** [comment]
this is not a valid pull request. close.

**Pull request closed without merging**
