### PR TITLE
fix one more Bug-1485134 from Bugzilla reported. Add WELS_B_MB_REC_VE…

### PR DESCRIPTION
**Pull request by xiaotiansf**
…RIFY to verify if ref picture is lost

### CODE REVIEW

**Comment by huili2** [comment]
It still reports other error like:
codec/decoder/core/src/deblocking.cpp:759:5: runtime error: index 14 out of bounds for type 'const int8_t [4]'

please check again.

**Comment by xiaotiansf** [comment]
Sure, I'll fix it and I am  currently tied with other work right now but will try to fix as soon as I can.

**Comment by xiaotiansf** [comment]
@huili2 Do you have Bugzilla bug number for the error: in codec/decoder/core/src/deblocking.cpp:759:5?

**Comment by huili2** [comment]
exactly the same one as 1485134.

**Comment by xiaotiansf** [comment]
That's strange and I don't see the run time error codec/decoder/core/src/deblocking.cpp:759:5 anymore after my latest PR #3014.

**Comment by xiaotiansf** [comment]
I mean I don't see the run time error anymore with the attached sample stream in Bug1485134.

**Comment by huili2** [comment]
Since you are not able to reproduce it (maybe my environment is different), let's bypass it and go on.

**Pull request merged**
