### PR TITLE
add SVC multilayer and SCC cases for travis binary comparison test

### PR DESCRIPTION
**Pull request by shihuade**
1.  add two bit streams

      ----Zhling_1280x720.264 (for SVC multi layer cases)
      ----Adobe_PDF_sample_a_1024x768_50Frms.264 (for SCC cases)

2. add two SHA1 tables
    ----Adobe_PDF_sample_a_1024x768_50Frms.264_AllCases_SHA1_Table.csv
    ----Zhling_1280x720.264_AllCases_SHA1_Table.csv

3.  remove CVPCMNL1_SVA_C.264 SHA1 table as BA_MW_D.264 has cover its cases

4.  update script based new SHA1 data structure
   script file run_BinarySHA1Comparison.sh
    ----remove MD5 check, SHA1 is good enough to check
    ----add "-lmaxb 0"   "-lmaxb 1"  "-lmaxb 2"  "-lmaxb 3"
    ----add "-loadbalancing"

### CODE REVIEW

**Comment by shihuade** [comment]
1. review board: 
  https://rbcommons.com/s/OpenH264/r/1705/
2. https://travis-ci.org/shihuade/openh264/builds/163618359

**Comment by shihuade** [comment]
1. case configure for SCC
   https://github.com/shihuade/Conformance-Test-Openh264/blob/master/CaseConfigure/case_SHA1Table_SCC.cfg

2. case configure for SVC
   https://github.com/shihuade/Conformance-Test-Openh264/blob/master/CaseConfigure/case_SHA1Table_SVC.cfg

3. case configure for SVC multiple layer
   https://github.com/shihuade/Conformance-Test-Openh264/blob/master/CaseConfigure/case_SHA1Table_SVC_MultiLayer.cfg

**Comment by shihuade** [comment]
https://travis-ci.org/shihuade/openh264/builds/163893060
https://travis-ci.org/shihuade/openh264/builds/163680630

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1705/

----
**testing_done**:  <p>https://travis-ci.org/shihuade/openh264/builds/163618359</p>
**description**:  <ol><li>add two bit streams<br />    ----Zhling_1280x720.264 (for SVC multi layer cases)<br />    ----Adobe_PDF_sample_a_1024x768_50Frms.264 (for SCC cases)</li></ol><p>2.add two SHA1 tables<br />    ----Adobe_PDF_sample_a_1024x768_50Frms.264_AllCases_SHA1_Table.csv<br />    ----Zhling_1280x720.264_AllCases_SHA1_Table.csv<br />3. remove CVPCMNL1_SVA_C.264 SHA1 table<br />   as BA_MW_D.264 has cover its cases</p><ol start="4" style="counter-reset: li 3"><li>update script based new SHA1 data structure<br />   script file run_BinarySHA1Comparison.sh<br />    ----remove MD5 check, SHA1 is good enough to check<br />    ----add "-lmaxb 0"   "-lmaxb 1"  "-lmaxb 2"  "-lmaxb 3"<br />    ----add "-loadbalancing"</li><li>for entire cases file, will be updated later when generated by jenkins in<br />   http://10.140.198.27:8080/view/OpenH264_SHATable_Test/job/Openh264_Travis_SHA1Table_Generation_weekly/</li></ol><p></p><p></p><h1>==========================================</h1><h1>test configure file, please refer to:</h1><ol><li><p>case configure for SCC<br />   https://github.com/shihuade/Conformance-Test-Openh264/blob/master/CaseConfigure/case_SHA1Table_SCC.cfg</p></li><li><p>case configure for SVC<br />   https://github.com/shihuade/Conformance-Test-Openh264/blob/master/CaseConfigure/case_SHA1Table_SVC.cfg</p></li><li><p>case configure for SVC multiple layer<br />   https://github.com/shihuade/Conformance-Test-Openh264/blob/master/CaseConfigure/case_SHA1Table_SVC_MultiLayer.cfg</p></li></ol>

----

----

----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1705/

**Pull request merged**
