### PR TITLE
fix bug of sps->direct_8x8_inference_flag setting

### PR DESCRIPTION
**Pull request by vacing**
related to #3401

### CODE REVIEW

**Comment by sijchen** [comment]
ITU-T H.264 (10/2016) A3.3.2 A-4, is only for Main .... Profile, should we add a profile check in this change ? thank you

**Comment by vacing** [comment]
> ITU-T H.264 (10/2016) A3.3.2 A-4, is only for Main .... Profile, should we add a profile check in this change ? thank you

yes, will fix

**Comment by vacing** [comment]
> change

> direct_8x8_inference_flag is not relevant to the Baseline, Constrained Baseline, Constrained High,
High 10 Intra, High 4:2:2 Intra, High 4:4:4 Intra, and CAVLC 4:4:4 Intra profiles as these profiles do not allow B slice
types, and direct_8x8_inference_flag is equal to 1 for all levels of the Extended profile.

I think we need not to check profile. If they didn't mention, it means they don't care the value; other profiles in annexes(svc mvc mvcd ) obey Table A-4.
BTW, direct_8x8_inference_flag set to 1 for all bitstreams now...

**Comment by vacing** [comment]
> ITU-T H.264 (10/2016) A3.3.2 A-4, is only for Main .... Profile, should we add a profile check in this change ? thank you

> > direct_8x8_inference_flag is not relevant to the Baseline, Constrained Baseline, Constrained High,
> > High 10 Intra, High 4:2:2 Intra, High 4:4:4 Intra, and CAVLC 4:4:4 Intra profiles as these profiles do not allow B slice
> > types, and direct_8x8_inference_flag is equal to 1 for all levels of the Extended profile.
> 
> I think we need not to check profile. If they didn't mention, it means they don't care the value; other profiles in annexes(svc mvc mvcd ) obey Table A-4.
> BTW, direct_8x8_inference_flag set to 1 for all bitstreams now...

**Comment by sijchen** [comment]
thank you for the contribution!

**Comment by sijchen** [comment]
I assume that we will need to update the binary values in UT after this PR merged, however, the Travis hook seems to be broken at this moment, we may update that later after the Travis hook is resumed. cc @huili2

**Comment by vacing** [comment]
> BTW, direct_8x8_inference_flag set to 1 for all bitstreams now...

thanks for merged, here I mean in x264

**Comment by mstorsjo** [comment]
> I assume that we will need to update the binary values in UT after this PR merged, however, the Travis hook seems to be broken at this moment, we may update that later after the Travis hook is resumed. cc @huili2

I made a PR to update those in #3407. Even if Travis isn't active, others may be running the tests externally.

**Pull request merged**
