### PR TITLE
update openh264 version

### PR DESCRIPTION
**Pull request by GuangweiWang**

### CODE REVIEW

**Comment by mcatanzaro** [comment]
Can you merge this into master as well, please? You don't want to leave the master branch with the older API version.

Looking forward to the release.

**Comment by xclaesse** [comment]
@GuangweiWang this PR is still missing in master branch I think.

**Comment by hmaarrfk** [comment]
I also hit the fact that this was missing in the master branch today.

**Comment by mcatanzaro** [comment]
> I also hit the fact that this was missing in the master branch today.

It's not though. It landed via 0c19a5c266275693484ed84edf6ff8cb7cd89d4e on the same day that Xavier complained in the comment above.

**Pull request merged**
