### PR TITLE
Bugzilla 1479656, 1485229 and 1486223 fixes

### PR DESCRIPTION
**Pull request by xiaotianshicomcast**

### CODE REVIEW

**Comment by mstorsjo** [comment]
This pull request also contains a version of the CAVLC B-frame support. As that is merged now, perhaps it's ok though, but it would be nicer to have it on a new plain branch without any extra commits.

**Comment by huili2** [comment]
This has duplicated code as other ones? Need close this one or not?

**Comment by xiaotiansf** [comment]
@sijchen I created a separate #PR3085 which only includes the Bugzilla fixes. So this #PR 3065 can be removed.

**Comment by huili2** [comment]
close this one as it is done by other PRs.

**Pull request closed without merging**
