### PR TITLE
[UT] add more special resolution and slice-mode tests

### PR DESCRIPTION
**Pull request by sijchen**
https://rbcommons.com/s/OpenH264/r/1686/

### CODE REVIEW

**Comment by mstorsjo** [comment]
Are all the new tests necessary here, or could some of them be removed?

The merged of this pull request made the runtime of the test suite significantly longer. On Travis, the runtime went from around 18 minutes (https://travis-ci.org/cisco/openh264/builds/157794575) to 40 minutes (https://travis-ci.org/cisco/openh264/builds/156316540). When running tests on ARM, each of the new tests take around 180 seconds, and there's 4 of them.

I understand that you want to test things thoroughly, but when the tests get this big (for not much added value), it can at worst force people to stop running the tests, just because it takes way too long.

**Comment by mstorsjo** [comment]
Also, when running the unit tests in valgrind (in order to make sure that there are no use of uninitialized memory, no memory leaks etc), the runtime of the unit test suite went from around 20-30 minutes to 65-80 minutes.

**Comment by sijchen** [comment]
@mstorsjo thx for the info, we will shorten these new test first and see if there is other things we can do to save some more time somewhere else.

**Comment by sijchen** [comment]
Archiving from https://rbcommons.com/s/OpenH264/r/1686/

----
**testing_done**:  
**description**:  add more special size test and slice modes

----

----
 reviewer Forrest Shi (huade) 
 time 2016-08-30T01:58:35+00:00 
2016-08-30T01:58:35+00:00 Forrest Shi (huade):
Ship it!

2016-08-30T01:58:35+00:00 Forrest Shi (huade):
 on **test/api/encode_options_test.cpp line1318**: 
 id="comment443353"><p>how about other cases, like more than 4 slices num</p>
how about other cases, like more than 4 slices num

2016-08-30T04:45:07+00:00 Sijia Chen (sijchen):
><p>like in line1308, this test does not intend to cover all possible input case, but just some specific ones. The all possible input case should be in another test case.</p>
like in line1308, this test does not intend to cover all possible input case, but just some specific ones. The all possible input case should be in another test case.

2016-08-30T04:45:07+00:00 Sijia Chen (sijchen):
 on **test/api/encode_options_test.cpp line1368**: 
 id="comment443354"><p>only test for size limited slice mode?</p><p>if <br />   SM_SIZELIMITED_SLICE != p.eSliceMode <br />then<br />  param_.uiMaxNalSize =0</p><p>got it</p>
only test for size limited slice mode?
if <br />   SM_SIZELIMITED_SLICE != p.eSliceMode <br />then<br />  param_.uiMaxNalSize =0
got it

2016-08-30T04:45:07+00:00 Sijia Chen (sijchen):
><p>only when SM_SIZELIMITED_SLICE we need to check NalSize</p>
only when SM_SIZELIMITED_SLICE we need to check NalSize


----
 reviewer Forrest Shi (huade) 
 time 2016-08-30T04:57:08+00:00 
2016-08-30T04:57:08+00:00 Forrest Shi (huade):
>Ship It!
Ship It!
Ship it!


----

----
2016-08-30T19:04:52+00:00 status-change:
https://github.com/cisco/openh264/pull/2550


----
 reviewer Forrest Shi (huade) 
 time 2016-08-31T04:16:08+00:00 
2016-08-31T04:16:08+00:00 Forrest Shi (huade):
>Ship It!
Ship It!
Ship it!


----
 reviewer Karina Li (ruil2) 
 time 2016-09-06T04:41:54+00:00 
2016-09-06T04:41:54+00:00 Karina Li (ruil2):
 on **test/api/encode_options_test.cpp line1320**: 
 id="comment445750"><p>why is 450 constant used?</p>
why is 450 constant used?

2016-09-06T17:44:56+00:00 Sijia Chen (sijchen):
><p>these two macros are not in the interface headers at present. To have a clear testing structure, the header files which is not the interfaces actually should be avoided in thes level of tests. So looks like the requirement is to move these macros into interface headers?</p>
450 is 400+50 in previous verion
prefer to use these macro definition instead of constant variable
these two macros are not in the interface headers at present. To have a clear testing structure, the header files which is not the interfaces actually should be avoided in thes level of tests. So looks like the requirement is to move these macros into interface headers?


----

Finish archiving from https://rbcommons.com/s/OpenH264/r/1686/

**Pull request merged**
